name: Build and Test
on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v4
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: 2.8.6
    - run: xmake -wvD
    - name: Test
      run: xmake run source | diff - expected.txt
      if: matrix.os != 'windows'
    - name: Test
      run: xmake run source
      if: matrix.os == 'windows'

